### ISSUE TITLE
clever

### ISSUE THREAD

**Issue by gedw99** [inkeliz/go_inkwasm#1]
Well done @inkeliz 

This is clearly the smart way to do it for perf !!! 

Its basically a code generator, that uses binding and parsing to produce faster calls ?

**Comment by inkeliz** [comment]
Yes, it will generate code to be used on WebAssembly Import (https://github.com/WebAssembly/design/blob/main/Modules.md#imports). Because all types (the input and output) is known at compile-time, the generated code is faster and avoids allocs (such as the `makeArgs` from `syscall/js`). The Import are Javascript Functions defined by you and set using the `WebAssembly.Module.imports` (the generated javascript will set it for you). 

----

You can also use `inkwasm` package directly, like `inkwasm.Global().Call("alert", "text")`. In general, it will be faster than `syscall/js` in most cases, due to zero-allocation, but slower than the generated code.

_Both methods also supports slices without copying, useful for WebGL._

-------

Of course, the `inkwasm` also uses the generator (it's already generated), so you can take a look into it.

For instance the `SetProperty` method:

https://github.com/inkeliz/go_inkwasm/blob/118895e42a8b2e4b02e24c2a022a7a3c37e1efca/inkwasm/wasm_js.go#L155-L160

That defines that `setProp` must call `Reflect.set`. The generator will generate the following code:

https://github.com/inkeliz/go_inkwasm/blob/118895e42a8b2e4b02e24c2a022a7a3c37e1efca/inkwasm/inkwasm_js.go#L123-L129

https://github.com/inkeliz/go_inkwasm/blob/118895e42a8b2e4b02e24c2a022a7a3c37e1efca/inkwasm/inkwasm_js.s#L124-L131

https://github.com/inkeliz/go_inkwasm/blob/118895e42a8b2e4b02e24c2a022a7a3c37e1efca/inkwasm/inkwasm_js.js#L128-L131

**Comment by gedw99** [comment]
thank you for all that info. I will give it a try...

i guess you don't know if this will be integrated into gio yet ?

**Comment by inkeliz** [comment]
It's unlike to be accepted on gio-core. You can see previous discussion around it on https://github.com/gioui/gio/pull/4 and https://lists.sr.ht/~eliasnaur/gio-patches/%3C160793741880.4602.2231951195088632162-0%40git.sr.ht%3E#%3C160793741880.4602.2231951195088632162-0@git.sr.ht%3E.

Also, some optimizations using `syscall/js` was already problematic, https://github.com/gioui/gio/pull/78#pullrequestreview-882743737. 

--------

Long history short, it bad for the maintainability and inkwasm can break in the future due to WebAssembly/Golang changes. The most important one is the removal of `CallImport` (https://github.com/golang/go/issues/38248), that will be private to `syscall/js` and `runtime`. That said, the generator will need to hack into runtime. Since we are on the runtime, we can also hack the `js.FuncOf` and maybe replace `syscall/js`.

--------

You can cherry-pick/rebase the change https://github.com/inkeliz/gio/commit/8e3119552f52d72c6a4965e878336456e2965883, it's compatible with gogio too. I'm doing to for months already. ;)

**Comment by gedw99** [comment]
again thanks for the link.   i think i understand..   Its a shame but for now this is how it is...
